# Generated by Django 3.1.4 on 2020-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologer',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate'),
        ),
    ]
