# Generated by Django 3.1.4 on 2020-12-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_astrologer_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astrologer',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='image',
            new_name='profile_image',
        ),
    ]
