# Generated by Django 3.1.4 on 2020-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201209_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astrologer',
            old_name='certificate',
            new_name='certificates',
        ),
        migrations.AddField(
            model_name='astrologer',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='astrologer',
            name='consultancy_types',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='astrologer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astrologer',
            name='experience',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='astrologer',
            name='languages',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='astrologer',
            name='qualificatons',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
